//! The two ways to reach a supervisor: a real board over serial, or the simulator.
//!
//! Both speak the identical protocol, which is the point. A test script written against the
//! simulator runs unchanged against hardware, and the only thing that changes is whether the
//! answers mean anything about a motor.

use std::io;
use std::time::Duration;

use stillair_core::console::PREFIX;

/// A bidirectional console link.
pub trait Link {
    /// Send one request line (without a trailing newline).
    fn send(&mut self, line: &str) -> io::Result<()>;

    /// Wait up to `timeout` for the next protocol line, returned without its prefix.
    /// `Ok(None)` means the timeout expired with nothing to report.
    fn receive(&mut self, timeout: Duration) -> io::Result<Option<String>>;

    /// Human-facing description, for error messages.
    fn describe(&self) -> String;

    /// Time elapsed on *this link's* clock: wall clock for a board, simulated time for the
    /// simulator. Callers time out against this rather than against their own clock,
    /// because the simulator runs as fast as the CPU allows and a wall-clock deadline
    /// would either never fire or fire immediately.
    fn elapsed(&self) -> Duration;
}

/// A real board on a serial port.
pub struct SerialLink {
    port: Box<dyn serialport::SerialPort>,
    path: String,
    /// Bytes read but not yet formed into a complete line.
    pending: String,
    opened_at: std::time::Instant,
}

impl SerialLink {
    pub fn open(path: &str) -> io::Result<Self> {
        let port = serialport::new(path, 115_200)
            .timeout(Duration::from_millis(50))
            .open()
            .map_err(|error| io::Error::other(format!("{path}: {error}")))?;
        Ok(Self {
            port,
            path: path.to_string(),
            pending: String::new(),
            opened_at: std::time::Instant::now(),
        })
    }

    /// Pull one complete line out of the buffer, if there is one.
    fn take_line(&mut self) -> Option<String> {
        let end = self.pending.find('\n')?;
        let line: String = self.pending.drain(..=end).collect();
        Some(line.trim_end_matches(['\r', '\n']).to_string())
    }
}

impl Link for SerialLink {
    fn send(&mut self, line: &str) -> io::Result<()> {
        use io::Write;
        self.port.write_all(line.as_bytes())?;
        self.port.write_all(b"\n")?;
        self.port.flush()
    }

    fn receive(&mut self, timeout: Duration) -> io::Result<Option<String>> {
        let deadline = std::time::Instant::now() + timeout;
        loop {
            // Log lines share this link and are passed through to stderr rather than
            // discarded — when a board misbehaves, its own log is usually the explanation.
            while let Some(line) = self.take_line() {
                if let Some(body) = line.strip_prefix(PREFIX) {
                    return Ok(Some(body.to_string()));
                }
                if !line.is_empty() {
                    eprintln!("{line}");
                }
            }
            if std::time::Instant::now() >= deadline {
                return Ok(None);
            }

            let mut chunk = [0u8; 256];
            match self.port.read(&mut chunk) {
                Ok(0) => {}
                Ok(read) => self
                    .pending
                    .push_str(&String::from_utf8_lossy(&chunk[..read])),
                Err(error) if error.kind() == io::ErrorKind::TimedOut => {}
                Err(error) => return Err(error),
            }
        }
    }

    fn describe(&self) -> String {
        self.path.clone()
    }

    fn elapsed(&self) -> Duration {
        self.opened_at.elapsed()
    }
}

/// Read a field out of one of the protocol's flat JSON objects.
///
/// Hand-rolled rather than pulling in a JSON parser: the schema is flat, fixed, and
/// generated by code in this same workspace, so the general case never arises.
pub fn field<'a>(json: &'a str, key: &str) -> Option<&'a str> {
    let needle = format!("\"{key}\":");
    let start = json.find(&needle)? + needle.len();
    let rest = &json[start..];
    if let Some(quoted) = rest.strip_prefix('"') {
        let end = quoted.find('"')?;
        return Some(&quoted[..end]);
    }
    let end = rest.find([',', '}']).unwrap_or(rest.len());
    Some(rest[..end].trim())
}

#[cfg(test)]
mod tests {
    use super::*;

    const FRAME: &str = "{\"type\":\"telemetry\",\"t\":12345,\"state\":\"running\",\
                         \"fault\":null,\"cmd_mrpm\":60000,\"dir\":\"fwd\"}";

    #[test]
    fn fields_are_extracted_by_type() {
        assert_eq!(field(FRAME, "t"), Some("12345"));
        assert_eq!(field(FRAME, "state"), Some("running"));
        assert_eq!(field(FRAME, "fault"), Some("null"));
        assert_eq!(field(FRAME, "cmd_mrpm"), Some("60000"));
        assert_eq!(field(FRAME, "dir"), Some("fwd"));
        assert_eq!(field(FRAME, "absent"), None);
    }

    #[test]
    fn a_key_that_is_a_prefix_of_another_does_not_match_it() {
        // "t" must not match "type". The needle includes the closing quote and colon,
        // which is what makes that true.
        assert_eq!(field(FRAME, "t"), Some("12345"));
        assert_ne!(field(FRAME, "t"), Some("telemetry"));
    }
}
